### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by trabant70** [yamada-github-account/cpprb#1]
Hi Yamada,

I am trying to install cpprb on Windows 10 but run into issues.
My setup includes GCC 9.2.0, Python 3.7.5, and Cython 0.29.14. 
It appears that the compilation finds build tools under Visual studio 2019 libraries but does not complete the install successfully. 
My question is whether there is any flag I could set to direct the installation to use GCC 9.2.0? I recompiled and installed GCC using Cygwin and it shows as available. Is there anything in the environmental variables that could be set to help find the right modules?

Thank you,

Reno Fiedler

**Comment by yamada-github-account** [comment]
Hi Reno,

Thank you for your contribution.

(By the way, this is the mirror repository of [this](https://gitlab.com/ymd_h/cpprb) and this issue page is open unintentionally, so that I will close this issue page on github as soon as you checked this.)

I strongly recommend to use virtual machine or container (e.g. docker), since build system on Windows is problematic. (e.g. lack of C++ standard features, memory size of `std::size_t` )

If you have any special reasons that you have to use Windows, the [cython official wiki](https://github.com/cython/cython/wiki/InstallingOnWindows) might be helpful.

**Comment by trabant70** [comment]
Thank you, I will check. It appears that the two flags -std:c++17 and -march=native are causing the Visual C++ compiler to fail. The former may need the colon where you have an = sign, the latter is not available at all (unless it would become available under c++17, had it accepted the flag as written). I tried other systems as well, incl. CodeBlock but no such luck. My Unix box is currently broken due to a failed processor, thus, windows.
